services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU19-ubuntu-22.04
    container_name: mssql
    pull_policy: if_not_present
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ThisIsMySaPass!123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
